import { combineReducers } from 'redux';
import BookReducer from './reducer_books'
import ActiveBook from './reducer_active_book';

const rootReducer = combineReducers({
  // key: reducer // คิดซะว่า key นี้ = ชื่อ state จาก redux นั้นแหละ
  books: BookReducer,
  activeBook: ActiveBook
});

export default rootReducer;

// reducer = function that return a piece of application state
// application can have many pieces of state
// so reducer does
/*
// application state - Generated by reducers
{
  books:[{title:'Harry Potter'},{title:'Javascript'}], // ค่าของ state Books มาจาก Books Reducer
  activeBook:{title:'Javascript:The Good Parts'} // ค่าของ state ActiveBook มาจาก ActiveBook Reducer
}
โดย state และ reducer จะถูก map ให้ถูกคู่โดยการใช้ combineReducers
*/

// Redux เป็นตัวคุม "application state"
// state = javascript object
// อย่าเมากับ component state นะ
// "component state" นั้นหมายถึง state ของ react ที่มี this.state.asdasd ,setState บลาๆให้ใช้ 
// ****ไม่เกี่ยวกัน**** คนสร้าง react , redux มันคนละคนกัน แต่ใช้ คำว่า state เหมือนกัน TT